# Generated by Django 4.2.5 on 2023-12-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationUpdateRequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationupdaterequest',
            name='id_update',
            field=models.IntegerField(default=0),
        ),
    ]
