# Generated by Django 4.2.5 on 2023-12-25 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locationUpdateRequest', '0002_locationupdaterequest_id_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationupdaterequest',
            name='geometry',
        ),
    ]
