# Generated by Django 4.2.5 on 2023-12-21 20:02

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/ImageLocations/')),
                ('category', models.CharField(choices=[('ALL', 'All'), ('SPORT', 'Sport'), ('CULTURE', 'Culture'), ('HISTORY', 'History'), ('FOOD_AND_DRINK', 'Food and drink'), ('OTHER', 'Other')], max_length=100)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('ONLY_ME', 'Only me'), ('LOGGED_USER', 'Logged user')], max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('active', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('last_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
